export const SET_COURSES = "SET_COURSES";
export const GET_CURRENT_COURSE = "GET_CURRENT_COURSES";
export const CURRENT_COURSE_SELECTED = "CURRENT_COURSE_SELECTED";
export const TEETIME_DATE_SELECTED = "TEETIME_DATE_SELECTED";
export const TEETIME_TIME_SELECTED = "TEETIME_TIME_SELECTED";
export const NEW_TEETIME_CREATED = "NEW_TEETIME_CREATED";
export const GROUP_SIZE_SELECTED = "GROUPSIZE_SELECTED";
export const GENDER_SELECTED = "GENDER_SELECTED";
export const HANDICAP_RANGE_SELECTED = "HANDICAP_RANGE_SELECTED";

export const SET_GOLFERS = "SET_GOLFERS";
export const GET_GOLFERS = "GET_GOLFERS";

export const SET_TEETIMES = "SET_TEETIMES";
export const GET_TEETIMES = "GET_TEETIMES";
