export const SET_COURSES = "SET_COURSES";
export const GET_CURRENT_COURSES = "GET_CURRENT_COURSES";

export const SET_GOLFERS = "SET_GOLFERS";
export const GET_GOLFERS = "GET_GOLFERS";

export const SET_TEETIMES = "SET_TEETIMES";
export const GET_TEETIMES = "GET_TEETIMES";

export const NEW_TEETIME_FORM_UPDATED = "NEW_TEETIME_FORM_UPDATED";
export const NEW_TEETIME_SAVE_STARTED = "NEW_TEETIME_SAVE_STARTED";
export const NEW_TEETIME_SAVE_SUCCEEDED = "NEW_TEETIME_SAVE_SUCCEEDED";
export const NEW_TEETIME_SAVE_FAILED = "NEW_TEETIME_SAVE_FAILED";
export const NEW_TEETIME_CLEARED = "NEW_TEETIME_CLEARED";

export const EDIT_TEETIME_FORM_UPDATED = "EDIT_TEETIME_FORM_UPDATED";
export const EDIT_TEETIME_SAVE_STARTED = "EDIT_TEETIME_SAVE_STARTED";
export const EDIT_TEETIME_SAVE_FAILED = "EDIT_TEETIME_SAVE_FAILED";
export const EDIT_TEETIME_SAVE_SUCCEEDED = "EDIT_TEETIME_SAVE_SUCCEEDED";
export const EDIT_TEETIME_CLEARED = "EDIT_TEETIME_CLEARED";
export const EDIT_TEETIME_LOADING_STARTED = "EDIT_TEETIME_LOADING_STARTED";
export const EDIT_TEETIME_LOADING_SUCCEEDED = "EDIT_TEETIME_LOADING_SUCCEEDED";
export const EDIT_TEETIME_LOADING_FAILED = "EDIT_TEETIME_LOADING_FAILED";
