const golfer = [
  {
    _id: "golfer_wertz_timmylwertz@gmail.com",
    type: "golfer",
    lastName: "Wertz",
    firstName: "Tim",
    handicap: 10,
    gender: "M",
    emailAddress: "timmylwertz@gmail.com"
  },
  {
    _id: "golfer_wertz_dlwertz@me.com",
    type: "golfer",
    lastName: "Wertz",
    firstName: "David",
    handicap: 7,
    gender: "M",
    emailAddress: "dlwertz@me.com"
  },
  {
    _id: "golfer_adkins_wkadki01@gmail.com",
    type: "golfer",
    lastName: "Adkins",
    firstName: "Will",
    handicap: 30,
    gender: "M",
    emailAddress: "wkadki01@gmail.com"
  },
  {
    _id: "golfer_estes_peternigelestes@gmail.com",
    type: "golfer",
    lastName: "Estes",
    firstName: "Peter",
    handicap: 30,
    gender: "M",
    emailAddress: "peternigelestes@gmail.com"
  },
  {
    _id: "golfer_liotti_bliotti@protonmail.com",
    type: "golfer",
    lastName: "Liotti",
    firstName: "Brian",
    handicap: 18,
    gender: "M",
    emailAddress: "bliotti@protonmail.com"
  },
  {
    _id: "golfer_hethcox_josh.hethcox@gmail.com",
    type: "golfer",
    lastName: "Hethcox",
    firstName: "Josh",
    handicap: 14,
    gender: "M",
    emailAddress: "josh.hethcox@gmail.com"
  },
  {
    _id: "golfer_paulsen_joshua@dynepic.com",
    type: "golfer",
    lastName: "Paulsen",
    firstName: "Josh",
    handicap: 10,
    gender: "M",
    emailAddress: "joshua@dynepic.com"
  },
  {
    _id: "golfer_boettcher_mvboettcher@gmail.com",
    type: "golfer",
    lastName: "Boettcher",
    firstName: "Max",
    handicap: 8,
    gender: "M",
    emailAddress: "mvboettcher@gmail.com"
  },
  {
    _id: "golfer_malley_laurenymalley@gmail.com",
    type: "golfer",
    lastName: "Malley",
    firstName: "Lauren",
    handicap: 12,
    gender: "F",
    emailAddress: "laurenymalley@gmail.com"
  },
  {
    _id: "golfer_wertz_kristinlwertz@gmail.com",
    type: "golfer",
    lastName: "Wertz",
    firstName: "Krist",
    handicap: 15,
    gender: "F",
    emailAddress: "kristinlwertz@gmail.com"
  },
  {
    _id: "golfer_wertz_jackie.wertz@gmail.com",
    type: "golfer",
    lastName: "Wertz",
    firstName: "Jackie",
    handicap: 20,
    gender: "F",
    emailAddress: "jackie.wertz@gmail.com"
  },
  {
    _id: "golfer_wertz_mldlwertz@aol.com",
    type: "golfer",
    lastName: "Wertz",
    firstName: "Mary Lou",
    handicap: 28,
    gender: "F",
    emailAddress: "mldlwertz@aol.com"
  }
];

const golfCourse = [
  {
    _id: "course_patriots-point-links",
    name: "Patriots Point Links",
    type: "course",
    phoneNumber: "(843) 881-0042",
    location: "1 Patriots Point Road, Mt Pleasant, SC 29464",
    image: "patriotspointlinks.jpg",
    address: {
      street: "1 Patriots Point Road",
      city: "Mt Pleasant",
      state: "SC",
      zip: "29464"
    },
    latitude: 32.7922,
    longitude: 79.8953,
    teeTimeWindow: [
      "8:00am - 10:00am",
      "9:00am - 11:00am",
      "10:00am - 12:00pm",
      "11:00am - 1:00pm",
      "12:00pm - 2:00pm",
      "1:00pm - 3:00pm",
      "2:00pm - 4:00pm",
      "3:00pm - 5:00pm"
    ],
    teeTimes: [
      { time: "8:00 AM", isAvail: true },
      { time: "8:10 AM", isAvail: true },
      { time: "8:20 AM", isAvail: true },
      { time: "8:30 AM", isAvail: true },
      { time: "8:40 AM", isAvail: true },
      { time: "8:50 AM", isAvail: true },
      { time: "9:00 AM", isAvail: true },
      { time: "9:10 AM", isAvail: true },
      { time: "9:20 AM", isAvail: true },
      { time: "9:30 AM", isAvail: true },
      { time: "9:40 AM", isAvail: true },
      { time: "9:50 AM", isAvail: true },
      { time: "10:00 AM", isAvail: true },
      { time: "10:10 AM", isAvail: true },
      { time: "10:20 AM", isAvail: true },
      { time: "10:30 AM", isAvail: true },
      { time: "10:40 AM", isAvail: true },
      { time: "10:50 AM", isAvail: true },
      { time: "11:00 AM", isAvail: true },
      { time: "11:10 AM", isAvail: true },
      { time: "11:20 AM", isAvail: true },
      { time: "11:30 AM", isAvail: true },
      { time: "11:40 AM", isAvail: true },
      { time: "11:50 AM", isAvail: true },
      { time: "12:00 PM", isAvail: true },
      { time: "12:10 PM", isAvail: true },
      { time: "12:20 PM", isAvail: true },
      { time: "12:30 PM", isAvail: true },
      { time: "12:40 PM", isAvail: true },
      { time: "12:50 PM", isAvail: true },
      { time: "1:00 PM", isAvail: true },
      { time: "1:10 PM", isAvail: true },
      { time: "1:20 PM", isAvail: true },
      { time: "1:30 PM", isAvail: true },
      { time: "1:40 PM", isAvail: true },
      { time: "1:50 PM", isAvail: true },
      { time: "2:00 PM", isAvail: true },
      { time: "2:10 PM", isAvail: true },
      { time: "2:20 PM", isAvail: true },
      { time: "2:30 PM", isAvail: true },
      { time: "2:40 PM", isAvail: true },
      { time: "2:50 PM", isAvail: true },
      { time: "3:00 PM", isAvail: true },
      { time: "3:10 PM", isAvail: true },
      { time: "3:20 PM", isAvail: true },
      { time: "3:30 PM", isAvail: true },
      { time: "3:40 PM", isAvail: true },
      { time: "3:50 PM", isAvail: true },
      { time: "4:00 PM", isAvail: true },
      { time: "4:10 PM", isAvail: true },
      { time: "4:20 PM", isAvail: true },
      { time: "4:30 PM", isAvail: true },
      { time: "4:40 PM", isAvail: true },
      { time: "4:50 PM", isAvail: true },
      { time: "5:00 PM", isAvail: true }
    ]
  },
  {
    _id: "course_city-of-charleston-golf-course",
    name: "City of Charleston Golf Course",
    type: "course",
    phoneNumber: "(843) 795-6517",
    location: "2110 Maybank Hwy, Charleston, 29412",
    image: "cityofcharlestongolfcourse.jpg",
    address: {
      street: "2110 Maybank Hwy",
      city: "Charleston",
      state: "SC",
      zip: "29412"
    },
    latitude: 32.7577,
    longitude: 79.9944,
    teeTimeWindow: [
      "8:00am - 10:00am",
      "9:00am - 11:00am",
      "10:00am - 12:00pm",
      "11:00am - 1:00pm",
      "12:00pm - 2:00pm",
      "1:00pm - 3:00pm",
      "2:00pm - 4:00pm",
      "3:00pm - 5:00pm"
    ],
    teeTimes: [
      { time: "8:00 AM", isAvail: true },
      { time: "8:10 AM", isAvail: true },
      { time: "8:20 AM", isAvail: true },
      { time: "8:30 AM", isAvail: true },
      { time: "8:40 AM", isAvail: true },
      { time: "8:50 AM", isAvail: true },
      { time: "9:00 AM", isAvail: true },
      { time: "9:10 AM", isAvail: true },
      { time: "9:20 AM", isAvail: true },
      { time: "9:30 AM", isAvail: true },
      { time: "9:40 AM", isAvail: true },
      { time: "9:50 AM", isAvail: true },
      { time: "10:00 AM", isAvail: true },
      { time: "10:10 AM", isAvail: true },
      { time: "10:20 AM", isAvail: true },
      { time: "10:30 AM", isAvail: true },
      { time: "10:40 AM", isAvail: true },
      { time: "10:50 AM", isAvail: true },
      { time: "11:00 AM", isAvail: true },
      { time: "11:10 AM", isAvail: true },
      { time: "11:20 AM", isAvail: true },
      { time: "11:30 AM", isAvail: true },
      { time: "11:40 AM", isAvail: true },
      { time: "11:50 AM", isAvail: true },
      { time: "12:00 PM", isAvail: true },
      { time: "12:10 PM", isAvail: true },
      { time: "12:20 PM", isAvail: true },
      { time: "12:30 PM", isAvail: true },
      { time: "12:40 PM", isAvail: true },
      { time: "12:50 PM", isAvail: true },
      { time: "1:00 PM", isAvail: true },
      { time: "1:10 PM", isAvail: true },
      { time: "1:20 PM", isAvail: true },
      { time: "1:30 PM", isAvail: true },
      { time: "1:40 PM", isAvail: true },
      { time: "1:50 PM", isAvail: true },
      { time: "2:00 PM", isAvail: true },
      { time: "2:10 PM", isAvail: true },
      { time: "2:20 PM", isAvail: true },
      { time: "2:30 PM", isAvail: true },
      { time: "2:40 PM", isAvail: true },
      { time: "2:50 PM", isAvail: true },
      { time: "3:00 PM", isAvail: true },
      { time: "3:10 PM", isAvail: true },
      { time: "3:20 PM", isAvail: true },
      { time: "3:30 PM", isAvail: true },
      { time: "3:40 PM", isAvail: true },
      { time: "3:50 PM", isAvail: true },
      { time: "4:00 PM", isAvail: true },
      { time: "4:10 PM", isAvail: true },
      { time: "4:20 PM", isAvail: true },
      { time: "4:30 PM", isAvail: true },
      { time: "4:40 PM", isAvail: true },
      { time: "4:50 PM", isAvail: true },
      { time: "5:00 PM", isAvail: true }
    ]
  },
  {
    _id: "course_the-ocean-couse-kiawah-island-golf-resort",
    name: "The Ocean Course, Kiawah Island Golf Resort",
    type: "course",
    phoneNumber: "(843) 768-2121",
    location: "1000 Ocean Course Drive, Johns Island, SC 29455",
    image: "oceancourse.jpg",
    address: {
      street: "1000 Ocean Course Drive",
      city: "Johns Island",
      state: "SC",
      zip: "29455"
    },
    latitude: 32.612,
    longitude: 80.0233,
    teeTimeWindow: [
      "8:00am - 10:00am",
      "9:00am - 11:00am",
      "10:00am - 12:00pm",
      "11:00am - 1:00pm",
      "12:00pm - 2:00pm",
      "1:00pm - 3:00pm",
      "2:00pm - 4:00pm",
      "3:00pm - 5:00pm"
    ],
    teeTimes: [
      { time: "8:00 AM", isAvail: true },
      { time: "8:10 AM", isAvail: true },
      { time: "8:20 AM", isAvail: true },
      { time: "8:30 AM", isAvail: true },
      { time: "8:40 AM", isAvail: true },
      { time: "8:50 AM", isAvail: true },
      { time: "9:00 AM", isAvail: true },
      { time: "9:10 AM", isAvail: true },
      { time: "9:20 AM", isAvail: true },
      { time: "9:30 AM", isAvail: true },
      { time: "9:40 AM", isAvail: true },
      { time: "9:50 AM", isAvail: true },
      { time: "10:00 AM", isAvail: true },
      { time: "10:10 AM", isAvail: true },
      { time: "10:20 AM", isAvail: true },
      { time: "10:30 AM", isAvail: true },
      { time: "10:40 AM", isAvail: true },
      { time: "10:50 AM", isAvail: true },
      { time: "11:00 AM", isAvail: true },
      { time: "11:10 AM", isAvail: true },
      { time: "11:20 AM", isAvail: true },
      { time: "11:30 AM", isAvail: true },
      { time: "11:40 AM", isAvail: true },
      { time: "11:50 AM", isAvail: true },
      { time: "12:00 PM", isAvail: true },
      { time: "12:10 PM", isAvail: true },
      { time: "12:20 PM", isAvail: true },
      { time: "12:30 PM", isAvail: true },
      { time: "12:40 PM", isAvail: true },
      { time: "12:50 PM", isAvail: true },
      { time: "1:00 PM", isAvail: true },
      { time: "1:10 PM", isAvail: true },
      { time: "1:20 PM", isAvail: true },
      { time: "1:30 PM", isAvail: true },
      { time: "1:40 PM", isAvail: true },
      { time: "1:50 PM", isAvail: true },
      { time: "2:00 PM", isAvail: true },
      { time: "2:10 PM", isAvail: true },
      { time: "2:20 PM", isAvail: true },
      { time: "2:30 PM", isAvail: true },
      { time: "2:40 PM", isAvail: true },
      { time: "2:50 PM", isAvail: true },
      { time: "3:00 PM", isAvail: true },
      { time: "3:10 PM", isAvail: true },
      { time: "3:20 PM", isAvail: true },
      { time: "3:30 PM", isAvail: true },
      { time: "3:40 PM", isAvail: true },
      { time: "3:50 PM", isAvail: true },
      { time: "4:00 PM", isAvail: true },
      { time: "4:10 PM", isAvail: true },
      { time: "4:20 PM", isAvail: true },
      { time: "4:30 PM", isAvail: true },
      { time: "4:40 PM", isAvail: true },
      { time: "4:50 PM", isAvail: true },
      { time: "5:00 PM", isAvail: true }
    ]
  },
  {
    _id: "course_daniel-island-club",
    name: "Daniel Island Club",
    type: "course",
    phoneNumber: "(843) 971-3555",
    location: "600 Island Park Drive, Charleston, SC 29492",
    image: "danielislandclub.jpg",
    address: {
      street: "600 Island Park Drive",
      city: "Charleston",
      state: "SC",
      zip: "29492"
    },
    latitude: 32.885,
    longitude: 79.9064,
    teeTimeWindow: [
      "8:00am - 10:00am",
      "9:00am - 11:00am",
      "10:00am - 12:00pm",
      "11:00am - 1:00pm",
      "12:00pm - 2:00pm",
      "1:00pm - 3:00pm",
      "2:00pm - 4:00pm",
      "3:00pm - 5:00pm"
    ],
    teeTimes: [
      { time: "8:00 AM", isAvail: true },
      { time: "8:10 AM", isAvail: true },
      { time: "8:20 AM", isAvail: true },
      { time: "8:30 AM", isAvail: true },
      { time: "8:40 AM", isAvail: true },
      { time: "8:50 AM", isAvail: true },
      { time: "9:00 AM", isAvail: true },
      { time: "9:10 AM", isAvail: true },
      { time: "9:20 AM", isAvail: true },
      { time: "9:30 AM", isAvail: true },
      { time: "9:40 AM", isAvail: true },
      { time: "9:50 AM", isAvail: true },
      { time: "10:00 AM", isAvail: true },
      { time: "10:10 AM", isAvail: true },
      { time: "10:20 AM", isAvail: true },
      { time: "10:30 AM", isAvail: true },
      { time: "10:40 AM", isAvail: true },
      { time: "10:50 AM", isAvail: true },
      { time: "11:00 AM", isAvail: true },
      { time: "11:10 AM", isAvail: true },
      { time: "11:20 AM", isAvail: true },
      { time: "11:30 AM", isAvail: true },
      { time: "11:40 AM", isAvail: true },
      { time: "11:50 AM", isAvail: true },
      { time: "12:00 PM", isAvail: true },
      { time: "12:10 PM", isAvail: true },
      { time: "12:20 PM", isAvail: true },
      { time: "12:30 PM", isAvail: true },
      { time: "12:40 PM", isAvail: true },
      { time: "12:50 PM", isAvail: true },
      { time: "1:00 PM", isAvail: true },
      { time: "1:10 PM", isAvail: true },
      { time: "1:20 PM", isAvail: true },
      { time: "1:30 PM", isAvail: true },
      { time: "1:40 PM", isAvail: true },
      { time: "1:50 PM", isAvail: true },
      { time: "2:00 PM", isAvail: true },
      { time: "2:10 PM", isAvail: true },
      { time: "2:20 PM", isAvail: true },
      { time: "2:30 PM", isAvail: true },
      { time: "2:40 PM", isAvail: true },
      { time: "2:50 PM", isAvail: true },
      { time: "3:00 PM", isAvail: true },
      { time: "3:10 PM", isAvail: true },
      { time: "3:20 PM", isAvail: true },
      { time: "3:30 PM", isAvail: true },
      { time: "3:40 PM", isAvail: true },
      { time: "3:50 PM", isAvail: true },
      { time: "4:00 PM", isAvail: true },
      { time: "4:10 PM", isAvail: true },
      { time: "4:20 PM", isAvail: true },
      { time: "4:30 PM", isAvail: true },
      { time: "4:40 PM", isAvail: true },
      { time: "4:50 PM", isAvail: true },
      { time: "5:00 PM", isAvail: true }
    ]
  },
  {
    _id: "course_wild-dunes-links-golf-course",
    name: "Wild Dunes Links Golf Course",
    type: "course",
    phoneNumber: "(843) 886-2002",
    location: "10001 Back Bay Drive, Isle of Palms, SC 29451",
    image: "wildduneslinks.jpg",
    address: {
      street: "10001 Back Bay Drive",
      city: "Isle of Palms",
      state: "SC",
      zip: "29451"
    },
    latitude: 32.8139,
    longitude: 79.7238,
    teeTimeWindow: [
      "8:00am - 10:00am",
      "9:00am - 11:00am",
      "10:00am - 12:00pm",
      "11:00am - 1:00pm",
      "12:00pm - 2:00pm",
      "1:00pm - 3:00pm",
      "2:00pm - 4:00pm",
      "3:00pm - 5:00pm"
    ],
    teeTimes: [
      { time: "8:00 AM", isAvail: true },
      { time: "8:10 AM", isAvail: true },
      { time: "8:20 AM", isAvail: true },
      { time: "8:30 AM", isAvail: true },
      { time: "8:40 AM", isAvail: true },
      { time: "8:50 AM", isAvail: true },
      { time: "9:00 AM", isAvail: true },
      { time: "9:10 AM", isAvail: true },
      { time: "9:20 AM", isAvail: true },
      { time: "9:30 AM", isAvail: true },
      { time: "9:40 AM", isAvail: true },
      { time: "9:50 AM", isAvail: true },
      { time: "10:00 AM", isAvail: true },
      { time: "10:10 AM", isAvail: true },
      { time: "10:20 AM", isAvail: true },
      { time: "10:30 AM", isAvail: true },
      { time: "10:40 AM", isAvail: true },
      { time: "10:50 AM", isAvail: true },
      { time: "11:00 AM", isAvail: true },
      { time: "11:10 AM", isAvail: true },
      { time: "11:20 AM", isAvail: true },
      { time: "11:30 AM", isAvail: true },
      { time: "11:40 AM", isAvail: true },
      { time: "11:50 AM", isAvail: true },
      { time: "12:00 PM", isAvail: true },
      { time: "12:10 PM", isAvail: true },
      { time: "12:20 PM", isAvail: true },
      { time: "12:30 PM", isAvail: true },
      { time: "12:40 PM", isAvail: true },
      { time: "12:50 PM", isAvail: true },
      { time: "1:00 PM", isAvail: true },
      { time: "1:10 PM", isAvail: true },
      { time: "1:20 PM", isAvail: true },
      { time: "1:30 PM", isAvail: true },
      { time: "1:40 PM", isAvail: true },
      { time: "1:50 PM", isAvail: true },
      { time: "2:00 PM", isAvail: true },
      { time: "2:10 PM", isAvail: true },
      { time: "2:20 PM", isAvail: true },
      { time: "2:30 PM", isAvail: true },
      { time: "2:40 PM", isAvail: true },
      { time: "2:50 PM", isAvail: true },
      { time: "3:00 PM", isAvail: true },
      { time: "3:10 PM", isAvail: true },
      { time: "3:20 PM", isAvail: true },
      { time: "3:30 PM", isAvail: true },
      { time: "3:40 PM", isAvail: true },
      { time: "3:50 PM", isAvail: true },
      { time: "4:00 PM", isAvail: true },
      { time: "4:10 PM", isAvail: true },
      { time: "4:20 PM", isAvail: true },
      { time: "4:30 PM", isAvail: true },
      { time: "4:40 PM", isAvail: true },
      { time: "4:50 PM", isAvail: true },
      { time: "5:00 PM", isAvail: true }
    ]
  },
  {
    _id: "course_shadowmoss-plantation-golf-club",
    name: "Shadowmoss Plantation Golf Club",
    type: "course",
    phoneNumber: "(843) 556-8251",
    location: "20 Dunvegan Drive, Charleston, SC 29414",
    image: "shadowmossplantation.jpg",
    address: {
      street: "20 Dunvegan Drive",
      city: "Charleston",
      state: "SC",
      zip: "29414"
    },
    latitude: 32.8426,
    longitude: 80.0733,
    teeTimeWindow: [
      "8:00am - 10:00am",
      "9:00am - 11:00am",
      "10:00am - 12:00pm",
      "11:00am - 1:00pm",
      "12:00pm - 2:00pm",
      "1:00pm - 3:00pm",
      "2:00pm - 4:00pm",
      "3:00pm - 5:00pm"
    ],
    teeTimes: [
      { time: "8:00 AM", isAvail: true },
      { time: "8:10 AM", isAvail: true },
      { time: "8:20 AM", isAvail: true },
      { time: "8:30 AM", isAvail: true },
      { time: "8:40 AM", isAvail: true },
      { time: "8:50 AM", isAvail: true },
      { time: "9:00 AM", isAvail: true },
      { time: "9:10 AM", isAvail: true },
      { time: "9:20 AM", isAvail: true },
      { time: "9:30 AM", isAvail: true },
      { time: "9:40 AM", isAvail: true },
      { time: "9:50 AM", isAvail: true },
      { time: "10:00 AM", isAvail: true },
      { time: "10:10 AM", isAvail: true },
      { time: "10:20 AM", isAvail: true },
      { time: "10:30 AM", isAvail: true },
      { time: "10:40 AM", isAvail: true },
      { time: "10:50 AM", isAvail: true },
      { time: "11:00 AM", isAvail: true },
      { time: "11:10 AM", isAvail: true },
      { time: "11:20 AM", isAvail: true },
      { time: "11:30 AM", isAvail: true },
      { time: "11:40 AM", isAvail: true },
      { time: "11:50 AM", isAvail: true },
      { time: "12:00 PM", isAvail: true },
      { time: "12:10 PM", isAvail: true },
      { time: "12:20 PM", isAvail: true },
      { time: "12:30 PM", isAvail: true },
      { time: "12:40 PM", isAvail: true },
      { time: "12:50 PM", isAvail: true },
      { time: "1:00 PM", isAvail: true },
      { time: "1:10 PM", isAvail: true },
      { time: "1:20 PM", isAvail: true },
      { time: "1:30 PM", isAvail: true },
      { time: "1:40 PM", isAvail: true },
      { time: "1:50 PM", isAvail: true },
      { time: "2:00 PM", isAvail: true },
      { time: "2:10 PM", isAvail: true },
      { time: "2:20 PM", isAvail: true },
      { time: "2:30 PM", isAvail: true },
      { time: "2:40 PM", isAvail: true },
      { time: "2:50 PM", isAvail: true },
      { time: "3:00 PM", isAvail: true },
      { time: "3:10 PM", isAvail: true },
      { time: "3:20 PM", isAvail: true },
      { time: "3:30 PM", isAvail: true },
      { time: "3:40 PM", isAvail: true },
      { time: "3:50 PM", isAvail: true },
      { time: "4:00 PM", isAvail: true },
      { time: "4:10 PM", isAvail: true },
      { time: "4:20 PM", isAvail: true },
      { time: "4:30 PM", isAvail: true },
      { time: "4:40 PM", isAvail: true },
      { time: "4:50 PM", isAvail: true },
      { time: "5:00 PM", isAvail: true }
    ]
  },
  {
    _id: "course_links-at-stono-ferry",
    name: "Links at Stono Ferry",
    type: "course",
    phoneNumber: "(843) 763-1817",
    location: "4812 Stono Links Drive, Hollywood, SC 29449",
    image: "linksatstonoferry.jpg",
    address: {
      street: "4812 Stono Links Drive",
      city: "Hollywood",
      state: "SC",
      zip: "29449"
    },
    latitude: 32.7565,
    longitude: 80.1612,
    teeTimeWindow: [
      "8:00am - 10:00am",
      "9:00am - 11:00am",
      "10:00am - 12:00pm",
      "11:00am - 1:00pm",
      "12:00pm - 2:00pm",
      "1:00pm - 3:00pm",
      "2:00pm - 4:00pm",
      "3:00pm - 5:00pm"
    ],
    teeTimes: [
      { time: "8:00 AM", isAvail: true },
      { time: "8:10 AM", isAvail: true },
      { time: "8:20 AM", isAvail: true },
      { time: "8:30 AM", isAvail: true },
      { time: "8:40 AM", isAvail: true },
      { time: "8:50 AM", isAvail: true },
      { time: "9:00 AM", isAvail: true },
      { time: "9:10 AM", isAvail: true },
      { time: "9:20 AM", isAvail: true },
      { time: "9:30 AM", isAvail: true },
      { time: "9:40 AM", isAvail: true },
      { time: "9:50 AM", isAvail: true },
      { time: "10:00 AM", isAvail: true },
      { time: "10:10 AM", isAvail: true },
      { time: "10:20 AM", isAvail: true },
      { time: "10:30 AM", isAvail: true },
      { time: "10:40 AM", isAvail: true },
      { time: "10:50 AM", isAvail: true },
      { time: "11:00 AM", isAvail: true },
      { time: "11:10 AM", isAvail: true },
      { time: "11:20 AM", isAvail: true },
      { time: "11:30 AM", isAvail: true },
      { time: "11:40 AM", isAvail: true },
      { time: "11:50 AM", isAvail: true },
      { time: "12:00 PM", isAvail: true },
      { time: "12:10 PM", isAvail: true },
      { time: "12:20 PM", isAvail: true },
      { time: "12:30 PM", isAvail: true },
      { time: "12:40 PM", isAvail: true },
      { time: "12:50 PM", isAvail: true },
      { time: "1:00 PM", isAvail: true },
      { time: "1:10 PM", isAvail: true },
      { time: "1:20 PM", isAvail: true },
      { time: "1:30 PM", isAvail: true },
      { time: "1:40 PM", isAvail: true },
      { time: "1:50 PM", isAvail: true },
      { time: "2:00 PM", isAvail: true },
      { time: "2:10 PM", isAvail: true },
      { time: "2:20 PM", isAvail: true },
      { time: "2:30 PM", isAvail: true },
      { time: "2:40 PM", isAvail: true },
      { time: "2:50 PM", isAvail: true },
      { time: "3:00 PM", isAvail: true },
      { time: "3:10 PM", isAvail: true },
      { time: "3:20 PM", isAvail: true },
      { time: "3:30 PM", isAvail: true },
      { time: "3:40 PM", isAvail: true },
      { time: "3:50 PM", isAvail: true },
      { time: "4:00 PM", isAvail: true },
      { time: "4:10 PM", isAvail: true },
      { time: "4:20 PM", isAvail: true },
      { time: "4:30 PM", isAvail: true },
      { time: "4:40 PM", isAvail: true },
      { time: "4:50 PM", isAvail: true },
      { time: "5:00 PM", isAvail: true }
    ]
  },
  {
    _id: "course_crowfield-golf-club",
    name: "Crowfield Golf Club",
    type: "course",
    phoneNumber: "(843) 764-4618",
    location: "300 Hamlet Cir, Goose Creek, SC 29445",
    image: "crowfield.jpg",
    address: {
      street: "300 Hamlet Circle",
      city: "Goose Creek",
      state: "SC",
      zip: "29455"
    },
    latitude: 33.0036,
    longitude: 80.0774,
    teeTimeWindow: [
      "8:00am - 10:00am",
      "9:00am - 11:00am",
      "10:00am - 12:00pm",
      "11:00am - 1:00pm",
      "12:00pm - 2:00pm",
      "1:00pm - 3:00pm",
      "2:00pm - 4:00pm",
      "3:00pm - 5:00pm"
    ],
    teeTimes: [
      { time: "8:00 AM", isAvail: true },
      { time: "8:10 AM", isAvail: true },
      { time: "8:20 AM", isAvail: true },
      { time: "8:30 AM", isAvail: true },
      { time: "8:40 AM", isAvail: true },
      { time: "8:50 AM", isAvail: true },
      { time: "9:00 AM", isAvail: true },
      { time: "9:10 AM", isAvail: true },
      { time: "9:20 AM", isAvail: true },
      { time: "9:30 AM", isAvail: true },
      { time: "9:40 AM", isAvail: true },
      { time: "9:50 AM", isAvail: true },
      { time: "10:00 AM", isAvail: true },
      { time: "10:10 AM", isAvail: true },
      { time: "10:20 AM", isAvail: true },
      { time: "10:30 AM", isAvail: true },
      { time: "10:40 AM", isAvail: true },
      { time: "10:50 AM", isAvail: true },
      { time: "11:00 AM", isAvail: true },
      { time: "11:10 AM", isAvail: true },
      { time: "11:20 AM", isAvail: true },
      { time: "11:30 AM", isAvail: true },
      { time: "11:40 AM", isAvail: true },
      { time: "11:50 AM", isAvail: true },
      { time: "12:00 PM", isAvail: true },
      { time: "12:10 PM", isAvail: true },
      { time: "12:20 PM", isAvail: true },
      { time: "12:30 PM", isAvail: true },
      { time: "12:40 PM", isAvail: true },
      { time: "12:50 PM", isAvail: true },
      { time: "1:00 PM", isAvail: true },
      { time: "1:10 PM", isAvail: true },
      { time: "1:20 PM", isAvail: true },
      { time: "1:30 PM", isAvail: true },
      { time: "1:40 PM", isAvail: true },
      { time: "1:50 PM", isAvail: true },
      { time: "2:00 PM", isAvail: true },
      { time: "2:10 PM", isAvail: true },
      { time: "2:20 PM", isAvail: true },
      { time: "2:30 PM", isAvail: true },
      { time: "2:40 PM", isAvail: true },
      { time: "2:50 PM", isAvail: true },
      { time: "3:00 PM", isAvail: true },
      { time: "3:10 PM", isAvail: true },
      { time: "3:20 PM", isAvail: true },
      { time: "3:30 PM", isAvail: true },
      { time: "3:40 PM", isAvail: true },
      { time: "3:50 PM", isAvail: true },
      { time: "4:00 PM", isAvail: true },
      { time: "4:10 PM", isAvail: true },
      { time: "4:20 PM", isAvail: true },
      { time: "4:30 PM", isAvail: true },
      { time: "4:40 PM", isAvail: true },
      { time: "4:50 PM", isAvail: true },
      { time: "5:00 PM", isAvail: true }
    ]
  },
  {
    _id: "course_dunes-west-golf-and-river-club",
    name: "Dunes West Golf and River Club",
    type: "course",
    phoneNumber: "(843) 856-9000",
    location: "3535 Wando Plantation Way, Mt Pleasant, SC 29466",
    image: "duneswest.jpg",
    address: {
      street: "3535 Wando Plantation Way",
      city: "Mt Pleasant",
      state: "SC",
      zip: "29466"
    },
    latitude: 32.9174,
    longitude: 79.7994,
    teeTimeWindow: [
      "8:00am - 10:00am",
      "9:00am - 11:00am",
      "10:00am - 12:00pm",
      "11:00am - 1:00pm",
      "12:00pm - 2:00pm",
      "1:00pm - 3:00pm",
      "2:00pm - 4:00pm",
      "3:00pm - 5:00pm"
    ],
    teeTimes: [
      { time: "8:00 AM", isAvail: true },
      { time: "8:10 AM", isAvail: true },
      { time: "8:20 AM", isAvail: true },
      { time: "8:30 AM", isAvail: true },
      { time: "8:40 AM", isAvail: true },
      { time: "8:50 AM", isAvail: true },
      { time: "9:00 AM", isAvail: true },
      { time: "9:10 AM", isAvail: true },
      { time: "9:20 AM", isAvail: true },
      { time: "9:30 AM", isAvail: true },
      { time: "9:40 AM", isAvail: true },
      { time: "9:50 AM", isAvail: true },
      { time: "10:00 AM", isAvail: true },
      { time: "10:10 AM", isAvail: true },
      { time: "10:20 AM", isAvail: true },
      { time: "10:30 AM", isAvail: true },
      { time: "10:40 AM", isAvail: true },
      { time: "10:50 AM", isAvail: true },
      { time: "11:00 AM", isAvail: true },
      { time: "11:10 AM", isAvail: true },
      { time: "11:20 AM", isAvail: true },
      { time: "11:30 AM", isAvail: true },
      { time: "11:40 AM", isAvail: true },
      { time: "11:50 AM", isAvail: true },
      { time: "12:00 PM", isAvail: true },
      { time: "12:10 PM", isAvail: true },
      { time: "12:20 PM", isAvail: true },
      { time: "12:30 PM", isAvail: true },
      { time: "12:40 PM", isAvail: true },
      { time: "12:50 PM", isAvail: true },
      { time: "1:00 PM", isAvail: true },
      { time: "1:10 PM", isAvail: true },
      { time: "1:20 PM", isAvail: true },
      { time: "1:30 PM", isAvail: true },
      { time: "1:40 PM", isAvail: true },
      { time: "1:50 PM", isAvail: true },
      { time: "2:00 PM", isAvail: true },
      { time: "2:10 PM", isAvail: true },
      { time: "2:20 PM", isAvail: true },
      { time: "2:30 PM", isAvail: true },
      { time: "2:40 PM", isAvail: true },
      { time: "2:50 PM", isAvail: true },
      { time: "3:00 PM", isAvail: true },
      { time: "3:10 PM", isAvail: true },
      { time: "3:20 PM", isAvail: true },
      { time: "3:30 PM", isAvail: true },
      { time: "3:40 PM", isAvail: true },
      { time: "3:50 PM", isAvail: true },
      { time: "4:00 PM", isAvail: true },
      { time: "4:10 PM", isAvail: true },
      { time: "4:20 PM", isAvail: true },
      { time: "4:30 PM", isAvail: true },
      { time: "4:40 PM", isAvail: true },
      { time: "4:50 PM", isAvail: true },
      { time: "5:00 PM", isAvail: true }
    ]
  },
  {
    _id: "course_legend-oaks-golf-club",
    name: "Legend Oaks Golf Club",
    type: "course",
    phoneNumber: "(843) 821-4077",
    location: "118 Legend Oaks Way, Summerville, SC 29485",
    image: "legendoaks.jpg",
    address: {
      street: "118 Legend Oaks Way",
      city: "Summerville",
      state: "SC",
      zip: "29485"
    },
    latitude: 32.9463,
    longitude: 80.2331,
    teeTimeWindow: [
      "8:00am - 10:00am",
      "9:00am - 11:00am",
      "10:00am - 12:00pm",
      "11:00am - 1:00pm",
      "12:00pm - 2:00pm",
      "1:00pm - 3:00pm",
      "2:00pm - 4:00pm",
      "3:00pm - 5:00pm"
    ],
    teeTimes: [
      { time: "8:00 AM", isAvail: true },
      { time: "8:10 AM", isAvail: true },
      { time: "8:20 AM", isAvail: true },
      { time: "8:30 AM", isAvail: true },
      { time: "8:40 AM", isAvail: true },
      { time: "8:50 AM", isAvail: true },
      { time: "9:00 AM", isAvail: true },
      { time: "9:10 AM", isAvail: true },
      { time: "9:20 AM", isAvail: true },
      { time: "9:30 AM", isAvail: true },
      { time: "9:40 AM", isAvail: true },
      { time: "9:50 AM", isAvail: true },
      { time: "10:00 AM", isAvail: true },
      { time: "10:10 AM", isAvail: true },
      { time: "10:20 AM", isAvail: true },
      { time: "10:30 AM", isAvail: true },
      { time: "10:40 AM", isAvail: true },
      { time: "10:50 AM", isAvail: true },
      { time: "11:00 AM", isAvail: true },
      { time: "11:10 AM", isAvail: true },
      { time: "11:20 AM", isAvail: true },
      { time: "11:30 AM", isAvail: true },
      { time: "11:40 AM", isAvail: true },
      { time: "11:50 AM", isAvail: true },
      { time: "12:00 PM", isAvail: true },
      { time: "12:10 PM", isAvail: true },
      { time: "12:20 PM", isAvail: true },
      { time: "12:30 PM", isAvail: true },
      { time: "12:40 PM", isAvail: true },
      { time: "12:50 PM", isAvail: true },
      { time: "1:00 PM", isAvail: true },
      { time: "1:10 PM", isAvail: true },
      { time: "1:20 PM", isAvail: true },
      { time: "1:30 PM", isAvail: true },
      { time: "1:40 PM", isAvail: true },
      { time: "1:50 PM", isAvail: true },
      { time: "2:00 PM", isAvail: true },
      { time: "2:10 PM", isAvail: true },
      { time: "2:20 PM", isAvail: true },
      { time: "2:30 PM", isAvail: true },
      { time: "2:40 PM", isAvail: true },
      { time: "2:50 PM", isAvail: true },
      { time: "3:00 PM", isAvail: true },
      { time: "3:10 PM", isAvail: true },
      { time: "3:20 PM", isAvail: true },
      { time: "3:30 PM", isAvail: true },
      { time: "3:40 PM", isAvail: true },
      { time: "3:50 PM", isAvail: true },
      { time: "4:00 PM", isAvail: true },
      { time: "4:10 PM", isAvail: true },
      { time: "4:20 PM", isAvail: true },
      { time: "4:30 PM", isAvail: true },
      { time: "4:40 PM", isAvail: true },
      { time: "4:50 PM", isAvail: true },
      { time: "5:00 PM", isAvail: true }
    ]
  },
  {
    _id: "course_rivertowne-country-club",
    name: "RiverTowne Country Club",
    type: "course",
    phoneNumber: "(843) 849-2400",
    location: "1700 Rivertowne Country Club Dr, Mt Pleasant, SC 29466",
    image: "rivertownecountryclub.jpg",
    address: {
      street: "1700 Rivertowne Country Club Drive",
      city: "Mt Pleasant",
      state: "SC",
      zip: "29466"
    },
    latitude: 32.8792,
    longitude: 79.8244,
    teeTimeWindow: [
      "8:00am - 10:00am",
      "9:00am - 11:00am",
      "10:00am - 12:00pm",
      "11:00am - 1:00pm",
      "12:00pm - 2:00pm",
      "1:00pm - 3:00pm",
      "2:00pm - 4:00pm",
      "3:00pm - 5:00pm"
    ],
    teeTimes: [
      { time: "8:00 AM", isAvail: true },
      { time: "8:10 AM", isAvail: true },
      { time: "8:20 AM", isAvail: true },
      { time: "8:30 AM", isAvail: true },
      { time: "8:40 AM", isAvail: true },
      { time: "8:50 AM", isAvail: true },
      { time: "9:00 AM", isAvail: true },
      { time: "9:10 AM", isAvail: true },
      { time: "9:20 AM", isAvail: true },
      { time: "9:30 AM", isAvail: true },
      { time: "9:40 AM", isAvail: true },
      { time: "9:50 AM", isAvail: true },
      { time: "10:00 AM", isAvail: true },
      { time: "10:10 AM", isAvail: true },
      { time: "10:20 AM", isAvail: true },
      { time: "10:30 AM", isAvail: true },
      { time: "10:40 AM", isAvail: true },
      { time: "10:50 AM", isAvail: true },
      { time: "11:00 AM", isAvail: true },
      { time: "11:10 AM", isAvail: true },
      { time: "11:20 AM", isAvail: true },
      { time: "11:30 AM", isAvail: true },
      { time: "11:40 AM", isAvail: true },
      { time: "11:50 AM", isAvail: true },
      { time: "12:00 PM", isAvail: true },
      { time: "12:10 PM", isAvail: true },
      { time: "12:20 PM", isAvail: true },
      { time: "12:30 PM", isAvail: true },
      { time: "12:40 PM", isAvail: true },
      { time: "12:50 PM", isAvail: true },
      { time: "1:00 PM", isAvail: true },
      { time: "1:10 PM", isAvail: true },
      { time: "1:20 PM", isAvail: true },
      { time: "1:30 PM", isAvail: true },
      { time: "1:40 PM", isAvail: true },
      { time: "1:50 PM", isAvail: true },
      { time: "2:00 PM", isAvail: true },
      { time: "2:10 PM", isAvail: true },
      { time: "2:20 PM", isAvail: true },
      { time: "2:30 PM", isAvail: true },
      { time: "2:40 PM", isAvail: true },
      { time: "2:50 PM", isAvail: true },
      { time: "3:00 PM", isAvail: true },
      { time: "3:10 PM", isAvail: true },
      { time: "3:20 PM", isAvail: true },
      { time: "3:30 PM", isAvail: true },
      { time: "3:40 PM", isAvail: true },
      { time: "3:50 PM", isAvail: true },
      { time: "4:00 PM", isAvail: true },
      { time: "4:10 PM", isAvail: true },
      { time: "4:20 PM", isAvail: true },
      { time: "4:30 PM", isAvail: true },
      { time: "4:40 PM", isAvail: true },
      { time: "4:50 PM", isAvail: true },
      { time: "5:00 PM", isAvail: true }
    ]
  },
  {
    _id: "course_wild-dunes-harbor",
    name: "Wild Dunes Harbor",
    type: "course",
    phoneNumber: "(843) 886-2301",
    location: "5881 Palmetto Dr, Isle of Palms, SC 29451",
    image: "wilddunesharbor.jpg",
    address: {
      street: "5881 Palmetto Drive",
      city: "Isle of Palms",
      state: "SC",
      zip: "29451"
    },
    latitude: 32.8055,
    longitude: 79.7388,
    teeTimeWindow: [
      "8:00am - 10:00am",
      "9:00am - 11:00am",
      "10:00am - 12:00pm",
      "11:00am - 1:00pm",
      "12:00pm - 2:00pm",
      "1:00pm - 3:00pm",
      "2:00pm - 4:00pm",
      "3:00pm - 5:00pm"
    ],
    teeTimes: [
      { time: "8:00 AM", isAvail: true },
      { time: "8:10 AM", isAvail: true },
      { time: "8:20 AM", isAvail: true },
      { time: "8:30 AM", isAvail: true },
      { time: "8:40 AM", isAvail: true },
      { time: "8:50 AM", isAvail: true },
      { time: "9:00 AM", isAvail: true },
      { time: "9:10 AM", isAvail: true },
      { time: "9:20 AM", isAvail: true },
      { time: "9:30 AM", isAvail: true },
      { time: "9:40 AM", isAvail: true },
      { time: "9:50 AM", isAvail: true },
      { time: "10:00 AM", isAvail: true },
      { time: "10:10 AM", isAvail: true },
      { time: "10:20 AM", isAvail: true },
      { time: "10:30 AM", isAvail: true },
      { time: "10:40 AM", isAvail: true },
      { time: "10:50 AM", isAvail: true },
      { time: "11:00 AM", isAvail: true },
      { time: "11:10 AM", isAvail: true },
      { time: "11:20 AM", isAvail: true },
      { time: "11:30 AM", isAvail: true },
      { time: "11:40 AM", isAvail: true },
      { time: "11:50 AM", isAvail: true },
      { time: "12:00 PM", isAvail: true },
      { time: "12:10 PM", isAvail: true },
      { time: "12:20 PM", isAvail: true },
      { time: "12:30 PM", isAvail: true },
      { time: "12:40 PM", isAvail: true },
      { time: "12:50 PM", isAvail: true },
      { time: "1:00 PM", isAvail: true },
      { time: "1:10 PM", isAvail: true },
      { time: "1:20 PM", isAvail: true },
      { time: "1:30 PM", isAvail: true },
      { time: "1:40 PM", isAvail: true },
      { time: "1:50 PM", isAvail: true },
      { time: "2:00 PM", isAvail: true },
      { time: "2:10 PM", isAvail: true },
      { time: "2:20 PM", isAvail: true },
      { time: "2:30 PM", isAvail: true },
      { time: "2:40 PM", isAvail: true },
      { time: "2:50 PM", isAvail: true },
      { time: "3:00 PM", isAvail: true },
      { time: "3:10 PM", isAvail: true },
      { time: "3:20 PM", isAvail: true },
      { time: "3:30 PM", isAvail: true },
      { time: "3:40 PM", isAvail: true },
      { time: "3:50 PM", isAvail: true },
      { time: "4:00 PM", isAvail: true },
      { time: "4:10 PM", isAvail: true },
      { time: "4:20 PM", isAvail: true },
      { time: "4:30 PM", isAvail: true },
      { time: "4:40 PM", isAvail: true },
      { time: "4:50 PM", isAvail: true },
      { time: "5:00 PM", isAvail: true }
    ]
  }
];

const teeTimes = [
  {
    _id: "teetime_course_wild-dunes-harbor_2018-08-25T08:00",
    date: "2018-08-25",
    time: "8:00 AM",
    courseId: "course_wild-dunes-harbor",
    type: "teetime",
    size: 4,
    hcpRange: {
      low: 0,
      high: 36
    },
    foursome: [
      {
        _id: "golfer_wertz_timmylwertz@gmail.com",
        type: "golfer",
        lastName: "Wertz",
        firstName: "Tim",
        handicap: 10,
        gender: "M",
        emailAddress: "timmylwertz@gmail.com"
      },
      {
        _id: "golfer_adkins_wkadki01@gmail.com",
        type: "golfer",
        lastName: "Adkins",
        firstName: "Will",
        handicap: 30,
        gender: "M",
        emailAddress: "wkadki01@gmail.com"
      },
      {
        _id: "golfer_estes_peternigelestes@gmail.com",
        type: "golfer",
        lastName: "Estes",
        firstName: "Peter",
        handicap: 30,
        gender: "M",
        emailAddress: "peternigelestes@gmail.com"
      },
      {
        _id: "golfer_malley_laurenymalley@gmail.com",
        type: "golfer",
        lastName: "Malley",
        firstName: "Lauren",
        handicap: 12,
        gender: "F",
        emailAddress: "laurenymalley@gmail.com"
      }
    ],
    primaryGolfer_id: "golfer_wertz_timmylwertz@gmail.com"
  },
  {
    _id: "teetime_course_wild-dunes-harbor_2018-08-25T10:00",
    date: "2018-08-25",
    time: "10:00 AM",
    courseId: "course_wild-dunes-harbor",
    type: "teetime",
    size: 4,
    hcpRange: {
      low: 10,
      high: 20
    },
    foursome: [
      {
        _id: "golfer_liotti_bliotti@protonmail.com",
        type: "golfer",
        lastName: "Liotti",
        firstName: "Brian",
        handicap: 18,
        gender: "M",
        emailAddress: "bliotti@protonmail.com"
      },
      {
        _id: "golfer_hethcox_josh.hethcox@gmail.com",
        type: "golfer",
        lastName: "Hethcox",
        firstName: "Josh",
        handicap: 14,
        gender: "M",
        emailAddress: "josh.hethcox@gmail.com"
      },
      {
        _id: "golfer_paulsen_joshua@dynepic.com",
        type: "golfer",
        lastName: "Paulsen",
        firstName: "Josh",
        handicap: 10,
        gender: "M",
        emailAddress: "joshua@dynepic.com"
      },
      {
        _id: "golfer_wertz_jackie.wertz@gmail.com",
        type: "golfer",
        lastName: "Wertz",
        firstName: "Jackie",
        handicap: 20,
        gender: "F",
        emailAddress: "jackie.wertz@gmail.com"
      }
    ],
    primaryGolfer_id: "golfer_liotti_bliotti@protonmail.com"
  },
  {
    _id: "teetime_course_wild-dunes-harbor-2018-08-25T02:20",
    date: "2018-08-25",
    time: "2:20 PM",
    courseId: "course_wild-dunes-harbor",
    type: "teetime",
    size: 4,
    hcpRange: {
      low: 5,
      high: 15
    },
    foursome: [
      {
        _id: "golfer_boettcher_mvboettcher@gmail.com",
        type: "golfer",
        lastName: "Boettcher",
        firstName: "Max",
        handicap: 8,
        gender: "M",
        emailAddress: "mvboettcher@gmail.com"
      },
      {
        _id: "golfer_malley_laurenymalley@gmail.com",
        type: "golfer",
        lastName: "Malley",
        firstName: "Lauren",
        handicap: 12,
        gender: "F",
        emailAddress: "laurenymalley@gmail.com"
      },
      {
        _id: "golfer_wertz_kristinlwertz@gmail.com",
        type: "golfer",
        lastName: "Wertz",
        firstName: "Krist",
        handicap: 15,
        gender: "F",
        emailAddress: "kristinlwertz@gmail.com"
      },
      {
        _id: "golfer_malley_laurenymalley@gmail.com",
        type: "golfer",
        lastName: "Malley",
        firstName: "Lauren",
        handicap: 12,
        gender: "F",
        emailAddress: "laurenymalley@gmail.com"
      }
    ],
    primaryGolfer_id: "golfer_boettcher_mvboettcher@gmail.com"
  },
  {
    _id: "teetime_course_city-of-charleston-golf-course_2018-08-26T08:40",
    date: "2018-08-26",
    time: "8:40 AM",
    courseId: "course_city-of-charleston-golf-course",
    type: "teetime",
    size: 4,
    hcpRange: {
      low: 0,
      high: 36
    },
    foursome: [
      {
        _id: "golfer_wertz_timmylwertz@gmail.com",
        type: "golfer",
        lastName: "Wertz",
        firstName: "Tim",
        handicap: 10,
        gender: "M",
        emailAddress: "timmylwertz@gmail.com"
      },
      {
        _id: "golfer_adkins_wkadki01@gmail.com",
        type: "golfer",
        lastName: "Adkins",
        firstName: "Will",
        handicap: 30,
        gender: "M",
        emailAddress: "wkadki01@gmail.com"
      },
      {
        _id: "golfer_estes_peternigelestes@gmail.com",
        type: "golfer",
        lastName: "Estes",
        firstName: "Peter",
        handicap: 30,
        gender: "M",
        emailAddress: "peternigelestes@gmail.com"
      },
      {
        _id: "golfer_malley_laurenymalley@gmail.com",
        type: "golfer",
        lastName: "Malley",
        firstName: "Lauren",
        handicap: 12,
        gender: "F",
        emailAddress: "laurenymalley@gmail.com"
      }
    ],
    primaryGolfer_id: "golfer_wertz_timmylwertz@gmail.com"
  },
  {
    _id: "teetime_course_city-of-charleston-golf-course-2018-08-26T01:20",
    date: "2018-08-26",
    time: "1:20 PM",
    courseId: "course_city-of-charleston-golf-course",
    type: "teetime",
    size: 4,
    hcpRange: {
      low: 10,
      high: 20
    },
    foursome: [
      {
        _id: "golfer_liotti_bliotti@protonmail.com",
        type: "golfer",
        lastName: "Liotti",
        firstName: "Brian",
        handicap: 18,
        gender: "M",
        emailAddress: "bliotti@protonmail.com"
      },
      {
        _id: "golfer_hethcox_josh.hethcox@gmail.com",
        type: "golfer",
        lastName: "Hethcox",
        firstName: "Josh",
        handicap: 14,
        gender: "M",
        emailAddress: "josh.hethcox@gmail.com"
      },
      {
        _id: "golfer_paulsen_joshua@dynepic.com",
        type: "golfer",
        lastName: "Paulsen",
        firstName: "Josh",
        handicap: 10,
        gender: "M",
        emailAddress: "joshua@dynepic.com"
      },
      {
        _id: "golfer_wertz_jackie.wertz@gmail.com",
        type: "golfer",
        lastName: "Wertz",
        firstName: "Jackie",
        handicap: 20,
        gender: "F",
        emailAddress: "jackie.wertz@gmail.com"
      }
    ],
    primaryGolfer_id: "golfer_liotti_bliotti@protonmail.com"
  },
  {
    _id: "teetime_course_city-of-charleston-golf-course-2018-08-26T03:20",
    date: "2018-08-26",
    time: "3:20 PM",
    courseId: "course_city-of-charleston-golf-course",
    type: "teetime",
    size: 4,
    hcpRange: {
      low: 5,
      high: 15
    },
    foursome: [
      {
        _id: "golfer_boettcher_mvboettcher@gmail.com",
        type: "golfer",
        lastName: "Boettcher",
        firstName: "Max",
        handicap: 8,
        gender: "M",
        emailAddress: "mvboettcher@gmail.com"
      },
      {
        _id: "golfer_malley_laurenymalley@gmail.com",
        type: "golfer",
        lastName: "Malley",
        firstName: "Lauren",
        handicap: 12,
        gender: "F",
        emailAddress: "laurenymalley@gmail.com"
      },
      {
        _id: "golfer_wertz_kristinlwertz@gmail.com",
        type: "golfer",
        lastName: "Wertz",
        firstName: "Krist",
        handicap: 15,
        gender: "F",
        emailAddress: "kristinlwertz@gmail.com"
      },
      {
        _id: "golfer_malley_laurenymalley@gmail.com",
        type: "golfer",
        lastName: "Malley",
        firstName: "Lauren",
        handicap: 12,
        gender: "F",
        emailAddress: "laurenymalley@gmail.com"
      }
    ],
    primaryGolfer_id: "golfer_boettcher_mvboettcher@gmail.com"
  },
  {
    _id: "teetime_course_links-at-stono-ferry_2018-08-27T11:00",
    date: "2018-08-27",
    time: "11:00 AM",
    courseId: "course_links-at-stono-ferry",
    type: "teetime",
    size: 4,
    hcpRange: {
      low: 0,
      high: 36
    },
    foursome: [
      {
        _id: "golfer_wertz_timmylwertz@gmail.com",
        type: "golfer",
        lastName: "Wertz",
        firstName: "Tim",
        handicap: 10,
        gender: "M",
        emailAddress: "timmylwertz@gmail.com"
      },
      {
        _id: "golfer_adkins_wkadki01@gmail.com",
        type: "golfer",
        lastName: "Adkins",
        firstName: "Will",
        handicap: 30,
        gender: "M",
        emailAddress: "wkadki01@gmail.com"
      },
      {
        _id: "golfer_estes_peternigelestes@gmail.com",
        type: "golfer",
        lastName: "Estes",
        firstName: "Peter",
        handicap: 30,
        gender: "M",
        emailAddress: "peternigelestes@gmail.com"
      },
      {
        _id: "golfer_malley_laurenymalley@gmail.com",
        type: "golfer",
        lastName: "Malley",
        firstName: "Lauren",
        handicap: 12,
        gender: "F",
        emailAddress: "laurenymalley@gmail.com"
      }
    ],
    primaryGolfer_id: "golfer_wertz_timmylwertz@gmail.com"
  },
  {
    _id: "teetime_course_links-at-stono-ferry_2018-08-27T1:20",
    date: "2018-08-27",
    time: "1:20 PM",
    courseId: "course_links-at-stono-ferry",
    type: "teetime",
    size: 4,
    hcpRange: {
      low: 10,
      high: 20
    },
    foursome: [
      {
        _id: "golfer_liotti_bliotti@protonmail.com",
        type: "golfer",
        lastName: "Liotti",
        firstName: "Brian",
        handicap: 18,
        gender: "M",
        emailAddress: "bliotti@protonmail.com"
      },
      {
        _id: "golfer_hethcox_josh.hethcox@gmail.com",
        type: "golfer",
        lastName: "Hethcox",
        firstName: "Josh",
        handicap: 14,
        gender: "M",
        emailAddress: "josh.hethcox@gmail.com"
      },
      {
        _id: "golfer_paulsen_joshua@dynepic.com",
        type: "golfer",
        lastName: "Paulsen",
        firstName: "Josh",
        handicap: 10,
        gender: "M",
        emailAddress: "joshua@dynepic.com"
      },
      {
        _id: "golfer_wertz_jackie.wertz@gmail.com",
        type: "golfer",
        size: 4,
        lastName: "Wertz",
        firstName: "Jackie",
        handicap: 20,
        gender: "F",
        emailAddress: "jackie.wertz@gmail.com"
      }
    ],
    primaryGolfer_id: "golfer_liotti_bliotti@protonmail.com"
  },
  {
    _id: "teetime_course_links-at-stono-ferry_2018-08-27T2:00",
    date: "2018-08-27",
    time: "2:00 PM",
    courseId: "course_links-at-stono-ferry",
    type: "teetime",
    size: 4,
    hcpRange: {
      low: 5,
      high: 15
    },
    foursome: [
      {
        _id: "golfer_boettcher_mvboettcher@gmail.com",
        type: "golfer",
        lastName: "Boettcher",
        firstName: "Max",
        handicap: 8,
        gender: "M",
        emailAddress: "mvboettcher@gmail.com"
      },
      {
        _id: "golfer_malley_laurenymalley@gmail.com",
        type: "golfer",
        lastName: "Malley",
        firstName: "Lauren",
        handicap: 12,
        gender: "F",
        emailAddress: "laurenymalley@gmail.com"
      },
      {
        _id: "golfer_wertz_kristinlwertz@gmail.com",
        type: "golfer",
        lastName: "Wertz",
        firstName: "Krist",
        handicap: 15,
        gender: "F",
        emailAddress: "kristinlwertz@gmail.com"
      },
      {
        _id: "golfer_malley_laurenymalley@gmail.com",
        type: "golfer",
        lastName: "Malley",
        firstName: "Lauren",
        handicap: 12,
        gender: "F",
        emailAddress: "laurenymalley@gmail.com"
      }
    ],
    primaryGolfer_id: "golfer_boettcher_mvboettcher@gmail.com"
  }
];
